[package]
name = "advent-of-code-2022"
version = "0.1.0"
authors = ["Indiana Kernick <indiana.kernick@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
text_io = "0.1"
pathfinding = "4"

[profile.release]
lto = true
strip = true
